name: Build Assets
on:
  workflow_call:

jobs:
  pipeline:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Prepare App
      uses: ./.github/workflows/prepare-app
    - name: Build Assets
      uses: ./.github/workflows/build-assets
