name: Check Code Style
on:
  workflow_call:

jobs:
  pipeline:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Prepare App
      uses: ./.github/workflows/prepare-app
    - name: Laravel Pint Test
      run: ./vendor/bin/pint --test
    # - name: Install Node & NPM dependencies
    #   uses: ./.github/workflows/install-npm-packages
    # - name: ESLint
    #   run: npm run lint
    # - name: Prettier
    #   run: npx prettier --check resources/
